- setup.py
shifter yesterday night experienced problems, when numexpr was not installed.
> add numexpr dependency

- setup.py
just version change, config file on server was changed to reflect updated current limits.
c.f.  https://trac.fact-project.org/wiki/DatatakingLimits
> update current limits

- shifthelper/__main__.py
- shifthelper/notifiers.py
> Call fallback shifter

- shifthelper/__main__.py
- shifthelper/checks.py
initial proposal for FactIntervalCheckers, which look at the website and decide if to `warn` or `info`
> checkers look at website

- shifthelper/checks/webdim.py
Adopt the new smart_fact_crawler API  in our current shifthelper production branch
> Try to adopt the novel smart_fact_crawler API

- README.md
- requirements.txt
- setup.py
- shifthelper/checks.py
- shifthelper/retry_smart_fact_crawler.py
- shifthelper/tools/is_shift.py
basically as the title says it, 
but I also found a bug an SQL query in `is_shift`. So in case you don't like this, I should at least merge that bugfix ... please have a look
> Adjust to sm crawler v 0.2.1

- README.md
- requirements.txt
- setup.py
- shifthelper/checks.py
- shifthelper/db_cloner/__main__.py
- shifthelper/retry_smart_fact_crawler.py
- shifthelper/tools/__init__.py
- shifthelper/tools/is_shift.py
- shifthelper/tools/whosonshift.py
tries to solve #109.
Is based on #113, so please merge that first ... or only merge this and kill #113.
> Only one db engine

- setup.py
- shifthelper/checks/retry_smart_fact_crawler.py
- shifthelper/checks/webdim.py
this is a PR for the master not long term running version.
It just adjusts for the retries needed to be done by the user of sfc
> adjust to new smart_fact_crawler v0.2.1

- README.md
- conda_env.yaml
- shifthelper/__main__.py
- shifthelper/logging.py
Use the json logger for log files, add more info to them
Also added deployment instructions using a conda env definition
> Improve logging

- shifthelper/__main__.py
- shifthelper/checks.py
fixes reason for connection problem mentioned in #118
> get url and credentials for webservice access from config.

- shifthelper/db_cloner/__main__.py
* pep8 and
* set cloning time to 15minutes
no issue related to this PR
> Clone less often

- shifthelper/__main__.py
- shifthelper/checks.py
- shifthelper/notifiers.py
- shifthelper/tools/__init__.py
- shifthelper/tools/is_shift.py
- shifthelper/tools/whosonshift.py
new check IsUserAwakeBeforeShutdown
TriggerRateLowForTenMinutes checks if is data taking
some pep8
> several new checks and other stuff

- shifthelper/notifiers.py
> use the hangup xml

- setup.py
- shifthelper/checks.py
> Fix retry mysql connection loss

- setup.py
- shifthelper/conditions.py
I think this might fix #157 
wasn't able to test it though.
> Fix regex issue

- shifthelper/conditions.py
Give the shifters some time to press the awake button before start calling them
> Give shifthelpers more time to press awake button

- shifthelper/checks.py
> Set alert limit for mrks to 60 Events / hour

- shifthelper/checks.py
> change default check interval to 2min

- shifthelper/db_cloner/__main__.py
The trick is to not just replace using pandas (which does `DROP TABLE, CREATE TABLE, INSERT stuff`) but save the new table into a temporary table and the rename it to the correct name. Renaming is atomic und thus does not lead to an exception like `table does not exist`
> Make cloning the db atomic, no more shifthelper mysql exceptions

- setup.py
- shifthelper/db_cloner/__main__.py
- shifthelper/tools/__init__.py
- shifthelper/tools/is_shift.py
- shifthelper/tools/shift.py
This fixes connection timeouts of the mysql db
> Db connect

- shifthelper/notifiers.py
title says it all @MaxNoe 
should we still do this before merging #234
> refactor `not_acknowledged_calls` into `not_acknowledged_messages`

- setup.py
- shifthelper/__main__.py
- shifthelper/conditions.py
- shifthelper/notifiers.py
- shifthelper/tools/__init__.py
- tests/test_acknowledging.py
- tests/test_conditions.py
SH checks now on the webinterface for the last time the https://github.com/fact-project/shifthelper_heartbeat_monitor has updated its timestamp. 
If the SH see a too old timestamp (10minutes), it starts calling a **developer**, so we can make sure the "heartbeat monitor" is really running.
This PR is connected to a PR in the webinterface of course.
https://github.com/fact-project/shifthelper_webinterface/pull/29
> Heartbeats

- setup.py
- shifthelper/db_cloner/__main__.py
> Db cloner issue #254

- shifthelper/__main__.py
- shifthelper/conditions.py
This should fix #257.
It was branched off `new_fsc` version, which is open PR #252. 
I've set the base to be `new_fsc`, in order to show how small the diff really is.
> Fix Parker mode
